#!/usr/bin/env bash

urlencode ()
{
    if [ $# -eq 0 ]; then
        echo "usage: urlencode <string>";
        return 1;
    fi
    python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])" $1;
}

urldecode ()
{
    if [ $# -eq 0 ]; then
        echo "usage: urldecode <string>";
        return 1;
    fi
    python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])" $1;
}

